[package]
name = "wolfssl"
version = "0.1.0"
edition = "2021"
authors = ["pete.m@expressvpn.com", "pang.t@expressvpn.com"]
license = "GPL-2.0"
description = "High-level bindings for WolfSSL"
repository = "https://github.com/expressvpn/wolfssl"
keywords = ["wolfssl", "vpn", "lightway", "post-quantum", "cryptography"]

[features]
debug = ["wolfssl-sys/debug"]

[dependencies]
wolfssl-sys = { git = "https://github.com/expressvpn/wolfssl-sys", features = ["postquantum"] }
thiserror = "1.0"
tokio = { version = "1.26.0", features = ["full"] }
bytes = "1.4.0"
parking_lot = "0.12.1"
tracing = "0.1.37"
tracing-attributes = "0.1.23"
pin-project = "1.0.12"
log = "0.4"

[dev-dependencies]
test-case = "3.0"
tracing-test = "0.2.4"
env_logger = "0.10.0"
once_cell = "1.17.1"
